version: '3.8'
services:
  redis:
    image: redis:5.0-alpine
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
  app:
    container_name: gcp-app
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8000
    env_file: ".env"
volumes:
  redis:
    driver: local